In [1]:
import cv2
import face_recognition as fr

In [23]:
img = cv2.imread('ano.jpeg',0)
cv2.imwrite('anogray.jpg',img)
img

array([[254, 254, 254, ..., 177, 178, 178],
       [254, 254, 254, ..., 170, 169, 168],
       [254, 254, 254, ..., 169, 166, 165],
       ..., 
       [ 56,  52,  49, ...,  80,  58,  49],
       [ 54,  51,  56, ...,  96,  75,  63],
       [ 49,  47,  60, ..., 106,  88,  59]], dtype=uint8)

In [24]:
known_image_clr = fr.load_image_file("test.jpg")
known_image_gray = fr.load_image_file("gray.jpg")
unknown = fr.load_image_file("anogray.jpg")
print(known_image_clr)
print(10*'----')
print(known_image_gray)

[[[127 127 127]
  [192 192 192]
  [188 188 188]
  ..., 
  [186 186 186]
  [186 186 186]
  [186 186 186]]

 [[193 193 193]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[188 188 188]
  [255 255 255]
  [254 254 254]
  ..., 
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ..., 
 [[ 75  57  71]
  [ 93  69  93]
  [ 95  72 101]
  ..., 
  [ 94  81 125]
  [ 87  92 134]
  [ 88  86 123]]

 [[ 72  64  77]
  [ 94  68  79]
  [ 93  75  91]
  ..., 
  [100  90 140]
  [ 94  95 139]
  [ 95  85 119]]

 [[ 66  55  72]
  [ 73  61  63]
  [ 78  69  74]
  ..., 
  [ 82  80 119]
  [ 79  80 110]
  [ 81  66  85]]]
----------------------------------------
[[[127 127 127]
  [191 191 191]
  [188 188 188]
  ..., 
  [186 186 186]
  [186 186 186]
  [186 186 186]]

 [[193 193 193]
  [255 255 255]
  [255 255 255]
  ..., 
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[187 187 187]
  [254 254 254]
  [254 254 254]
  ..., 
  [254 254 254]
  [254 254 254]
  [254 254 254]]

In [25]:
clr_encoding = fr.face_encodings(known_image_clr)
gray_encoding = fr.face_encodings(known_image_gray)
unknown_encoding = fr.face_encodings(unknown)
print(clr_encoding[0])
print(10*'-----')
print(gray_encoding[0])

[-0.18210861  0.08323935  0.04100934 -0.08456755 -0.03903438 -0.00052535
 -0.09172285 -0.09499853  0.20425405 -0.152217    0.1835601   0.10543621
 -0.14426562 -0.13123442  0.00551013  0.06126467 -0.14778879 -0.16028249
 -0.0545084  -0.06595586  0.0297726   0.0039091   0.03987272  0.02599402
 -0.21882659 -0.31936195 -0.09300435 -0.06492978  0.01585343 -0.06812251
  0.00907398 -0.01106164 -0.21918117 -0.0300983  -0.00837708  0.19261198
 -0.06266408  0.03099868  0.18897918 -0.00285382 -0.18190423  0.02147613
  0.00990355  0.26627213  0.1959921   0.02377295 -0.00669104 -0.04518633
  0.19141169 -0.25171778  0.12977961  0.12057616  0.110389    0.05610513
  0.11823515 -0.14524549  0.04858059  0.15715273 -0.18796082  0.04249811
 -0.01568665 -0.12619269 -0.02498481  0.04615731  0.18637349  0.17889924
 -0.07154342 -0.16771351  0.17731388 -0.12430965  0.00914981  0.14299011
 -0.06959803 -0.17490926 -0.28993016  0.05728671  0.43131503  0.15918131
 -0.14274177  0.0521556  -0.08347168 -0.00415712  0

In [26]:
import numpy as np
print(np.linalg.norm(clr_encoding[0]-unknown_encoding[0]))
print(np.linalg.norm(gray_encoding[0]-unknown_encoding[0]))

0.37098680687
0.372213355074
